name: Python CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get update && apt-get install libgl1
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest
